/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/recruits/{recruitId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 모집 수정
         * @description 모집 정보를 수정합니다.
         */
        put: operations["updateRecruit"];
        post?: never;
        /**
         * 모집 취소
         * @description 모집 정보를 제거합니다.
         */
        delete: operations["cancelRecruit"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/recruits/{recruitId}/force-update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 모집 정보 강제 수정
         * @description 마감 여부와 관계없이 모집 정보를 강제로 수정합니다.
         */
        put: operations["updateRecruit_1"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/mails/scenarios/{scenarioId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 시나리오 수정
         * @description 기존 메일 발송 시나리오를 수정합니다.
         */
        put: operations["updateScenario"];
        post?: never;
        /**
         * 시나리오 삭제
         * @description 메일 발송 시나리오를 삭제합니다.
         */
        delete: operations["deleteScenario"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/applies/{applyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 지원서 상세 조회
         * @description 전달한 ID에 해당하는 지원서의 상세 정보를 조회합니다.
         */
        get: operations["findApply"];
        /**
         * 제출된 지원서 수정
         * @description 전달한 ID에 해당하는 제출된 지원서의 정보를 수정합니다.
         */
        put: operations["editSubmittedApply"];
        post?: never;
        /**
         * 지원서 삭제
         * @description 전달한 ID에 해당하는 지원서를 삭제합니다.
         */
        delete: operations["deleteApply"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/semesters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 기수 등록
         * @description 새로운 기수를 등록합니다.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/semesters/{semesterId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 기수별 행사 목록 조회
         * @description 선택한 기수와 행사 타입의 행사 목록을 조회합니다.
         */
        get: operations["getEvents"];
        put?: never;
        /**
         * 기수별 행사 일괄 편집
         * @description 선택한 기수의 행사 추가와 이름 수정을 원자적으로 처리합니다.
         */
        post: operations["editEvents"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/recruits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 모집 등록
         * @description 모집 정보를 등록합니다.
         */
        post: operations["registerRecruit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/members/supporters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 운영 서포터즈 구성원 목록 조회
         * @description 운영 서포터즈 구성원 목록을 조회합니다.
         */
        get: operations["getAdminMemberSupportersList"];
        put?: never;
        /**
         * 운영 서포터즈 구성원 추가
         * @description 운영 서포터즈 구성원을 추가합니다.
         */
        post: operations["createAdminMemberSupporters"];
        /**
         * 운영 서포터즈 구성원 일괄 삭제
         * @description 선택한 운영 서포터즈 구성원을 일괄 삭제합니다. 유효하지 않은 ID가 있으면 전체 요청이 실패합니다.
         */
        delete: operations["deleteAdminMemberSupportersList"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/members/semester": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 일반 구성원 리스트 조회
         * @description 일반 구성원 목록을 커서기반 페이징과 필터를 적용해 조회합니다.
         */
        get: operations["searchAdminMemberSemesterList"];
        put?: never;
        /**
         * 일반 구성원 추가
         * @description 일반 구성원을 추가합니다.
         */
        post: operations["createAdminMemberSemester"];
        /**
         * 일반 구성원 일괄 삭제
         * @description 선택한 일반 구성원을 일괄 삭제합니다.
         */
        delete: operations["deleteAdminMemberSemesterList"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/members/makers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 메이커스팀 구성원 목록 조회
         * @description 메이커스팀 구성원 목록을 조회합니다.
         */
        get: operations["getAdminMemberMakersList"];
        put?: never;
        /**
         * 메이커스팀 구성원 추가
         * @description 메이커스팀 구성원을 추가합니다.
         */
        post: operations["createAdminMemberMakers"];
        /**
         * 메이커스팀 구성원 일괄 삭제
         * @description 선택한 메이커스팀 구성원을 일괄 삭제합니다. 유효하지 않은 ID가 있으면 전체 요청이 실패합니다.
         */
        delete: operations["deleteAdminMemberMakersList"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/mails/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 메일 템플릿 목록 조회
         * @description 메일 템플릿을 구분과 타입으로 필터링하여 최신순으로 조회합니다.
         */
        get: operations["searchScenarios"];
        put?: never;
        /**
         * 시나리오 생성
         * @description 새로운 메일 발송 시나리오를 생성합니다.
         */
        post: operations["createScenario"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/mails/scenarios/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 메일 미리보기
         * @description 지원자와 입력 변수 기준으로 메일 제목과 본문을 미리 확인합니다.
         */
        post: operations["preview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/mails/dispatches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 단체 메일 발송
         * @description 선택한 제출 지원자에게 메일을 발송하고 대상별 결과를 기록합니다.
         */
        post: operations["sendMail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/emails/send/manual": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 템플릿 이메일 단건 발송
         * @description 선택된 템플릿으로 단건 이메일을 발송합니다.
         */
        post: operations["sendManualTemplatedEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/emails/send/manual/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 템플릿 이메일 일괄 발송
         * @description 선택된 템플릿으로 여러 이메일을 발송합니다.
         */
        post: operations["sendManualBulkTemplatedEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/apply/pass": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 지원자 합격
         * @description 지원자를 합격 처리하여 구성원으로 승인합니다.
         */
        post: operations["passApply"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 관리자 계정 목록 조회
         * @description 관리자 계정 목록을 조회합니다. 계정 유형과 상태를 복수 필터로 선택할 수 있습니다.
         */
        get: operations["findAccounts"];
        put?: never;
        /**
         * 관리자 계정 생성
         * @description 관리자 계정 유형의 계정을 생성합니다.
         */
        post: operations["createAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin-auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 관리자 로그아웃
         * @description 관리자가 로그아웃합니다.
         */
        post: operations["logoutAdmin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin-auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 관리자 로그인
         * @description 관리자 로그인을 시도합니다.
         */
        post: operations["loginAdmin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/members/supporters/{memberActivityId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 운영 서포터즈 구성원 상세 조회
         * @description 운영 서포터즈 구성원을 상세 조회합니다.
         */
        get: operations["getAdminMemberSupportersDetail"];
        put?: never;
        post?: never;
        /**
         * 운영 서포터즈 구성원 삭제
         * @description 전달한 활동 ID에 해당하는 운영 서포터즈 구성원을 삭제합니다.
         */
        delete: operations["deleteAdminMemberSupporters"];
        options?: never;
        head?: never;
        /**
         * 운영 서포터즈 구성원 수정
         * @description 전달한 활동 ID에 해당하는 운영 서포터즈 구성원의 입력된 정보만 수정합니다.
         */
        patch: operations["editAdminMemberSupporters"];
        trace?: never;
    };
    "/admin/members/semester/{memberActivityId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 일반 구성원 단건 조회
         * @description 일반 구성원 정보와 기수별 행사 참여 상태를 조회합니다.
         */
        get: operations["getMemberSemester"];
        put?: never;
        post?: never;
        /**
         * 일반 구성원 삭제
         * @description 일반 구성원을 삭제합니다.
         */
        delete: operations["deleteAdminMemberSemester"];
        options?: never;
        head?: never;
        /**
         * 일반 구성원 수정
         * @description 일반 구성원의 기본정보와 활동정보를 수정합니다.
         */
        patch: operations["editAdminMemberSemester"];
        trace?: never;
    };
    "/admin/members/semester/{memberActivityId}/event-participation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 일반 구성원 행사 참여 상태 수정
         * @description 일반 구성원의 기수별 행사 참여 상태를 수정합니다. 참여 상태가 null이면 미지정 처리합니다.
         */
        patch: operations["editEventParticipation"];
        trace?: never;
    };
    "/admin/members/makers/{memberActivityId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 메이커스팀 구성원 상세 조회
         * @description 메이커스팀 구성원을 상세 조회합니다.
         */
        get: operations["getAdminMemberMakersDetail"];
        put?: never;
        post?: never;
        /**
         * 메이커스팀 구성원 삭제
         * @description 전달한 활동 ID에 해당하는 메이커스팀 구성원을 삭제합니다.
         */
        delete: operations["deleteAdminMemberMakers"];
        options?: never;
        head?: never;
        /**
         * 메이커스팀 구성원 수정
         * @description 전달한 활동 ID에 해당하는 메이커스팀 구성원의 입력된 정보만 수정합니다.
         */
        patch: operations["editAdminMemberMakers"];
        trace?: never;
    };
    "/admin/applies/selection-results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 지원자 선정 결과 일괄 변경
         * @description 제출 완료된 지원자들의 선정 결과와 예비 번호를 일괄 변경합니다.
         */
        patch: operations["updateSelectionResults"];
        trace?: never;
    };
    "/admin/accounts/{memberId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 관리자 계정 정보 수정
         * @description 관리자 계정의 이메일, 이름, 권한, 활성화 상태를 수정합니다.
         */
        patch: operations["updateAccount"];
        trace?: never;
    };
    "/admin/accounts/{memberId}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 관리자 계정 권한 수정
         * @description 관리자 계정의 권한을 수정합니다.
         */
        patch: operations["updateRole"];
        trace?: never;
    };
    "/admin/accounts/{memberId}/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 관리자 계정 활성화 상태 수정
         * @description 관리자 계정을 활성화하거나 비활성화합니다.
         */
        patch: operations["updateActive"];
        trace?: never;
    };
    "/admin/accounts/members/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 관리자 계정 일괄 비활성화
         * @description 요청한 관리자 계정을 일괄 비활성화합니다. 활성화는 단건 API를 사용합니다.
         */
        patch: operations["deactivateAccounts"];
        trace?: never;
    };
    "/admin/mails/targets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 메일 발송 대상자 조회
         * @description 모집 공고와 선정 결과로 메일 발송 대상자를 조회합니다.
         */
        get: operations["searchTargets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/mails/scenarios/{scenarioId}/variables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 시나리오 변수 목록 조회
         * @description 시나리오 ID로 템플릿 변수 목록(공통/개인)을 조회합니다.
         */
        get: operations["getVariablesByScenario"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/mails/recruits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 메일 발송용 모집 공고 목록 조회
         * @description 메일 발송 기준으로 사용할 모집 공고를 등록일 최신순으로 조회합니다.
         */
        get: operations["getRecruits"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/applies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 지원서 목록 조회
         * @description 지원서들의 목록을 조회합니다. 모집 공고, 모집 유형, 모집 사유, 기수, 직군, 지원 상태로 필터링할 수 있습니다.
         */
        get: operations["findApplies"];
        put?: never;
        post?: never;
        /**
         * 지원서 다수 삭제
         * @description 선택한 다수의 지원서들을 삭제합니다. 삭제한 수를 반환합니다.
         */
        delete: operations["deleteSubmittedApplies"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/semesters/{semesterId}/events/{semesterEventId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 기수별 행사 삭제
         * @description 선택한 기수의 행사를 삭제합니다.
         */
        delete: operations["deleteEvent"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        JobFamily: "PM" | "PD" | "FE" | "BE" | "APP" | "SUPPORTER" | "OPS" | "INFRA" | "BX" | "ER";
        RecruitFaq: {
            title?: string;
            content?: string;
        };
        RecruitFaqRequest: {
            title: string;
            content: string;
        };
        RecruitUpdateRequest: {
            jobFamily: components["schemas"]["JobFamily"];
            /** Format: date-time */
            startDate: string;
            /** Format: date-time */
            endDate: string;
            summary?: string;
            recruitInformation?: string;
            notice?: string;
            faqs?: components["schemas"]["RecruitFaqRequest"][];
            faqsOrNull?: components["schemas"]["RecruitFaq"][];
        };
        CustomVariableRequest: {
            key: string;
            label: string;
            inputType: components["schemas"]["VariableInputType"];
            required?: boolean;
            description?: string;
        };
        /** @enum {string} */
        MailScenarioCategory: "GENERAL" | "CLUB_MEMBER" | "MAKERS" | "SUPPORTERS";
        MailScenarioRequest: {
            name: string;
            category: components["schemas"]["MailScenarioCategory"];
            type: components["schemas"]["MailScenarioType"];
            scenarioCode: string;
            subjectTemplate: string;
            bodyTemplate: string;
            active: boolean;
            customVariables: components["schemas"]["CustomVariableRequest"][];
        };
        /** @enum {string} */
        MailScenarioType: "FIRST_PASS" | "FINAL_PASS" | "STANDBY_PASS" | "REJECT" | "ETC";
        /** @enum {string} */
        VariableInputType: "TEXT" | "URL" | "EMAIL" | "PHONE" | "DATE_TIME";
        CustomVariableResponse: {
            key?: string;
            label?: string;
            inputType?: string;
            required?: boolean;
            description?: string;
        };
        MailScenarioResponse: {
            /** Format: int64 */
            id?: number;
            name?: string;
            category?: components["schemas"]["MailScenarioCategory"];
            type?: components["schemas"]["MailScenarioType"];
            scenarioCode?: string;
            subjectTemplate?: string;
            bodyTemplate?: string;
            active?: boolean;
            /** Format: date-time */
            createdAt?: string;
            customVariables?: components["schemas"]["CustomVariableResponse"][];
        };
        ApplyPortfolioDto: {
            fileUrl?: string;
            fileName?: string;
            fileSize?: string;
            sequence?: string;
        };
        SubmittedApplyEditRequest: {
            name: string;
            phoneNumber: string;
            email: string;
            jobFamily: components["schemas"]["JobFamily"];
            answers: {
                [key: string]: string;
            };
            portfolios?: components["schemas"]["ApplyPortfolioDto"][];
        };
        RecruitRegisterRequest: {
            jobFamily: components["schemas"]["JobFamily"];
            /** Format: date-time */
            startDate: string;
            /** Format: date-time */
            endDate: string;
            summary?: string;
            recruitInformation?: string;
            notice?: string;
            faqs?: components["schemas"]["RecruitFaqRequest"][];
        };
        SemesterRegisterRequest: {
            name?: string;
            recruitRegisterRequests?: components["schemas"]["RecruitRegisterRequest"][];
        };
        CreateSemesterEventRequest: {
            name: string;
        };
        EditSemesterEventsRequest: {
            type: components["schemas"]["SemesterEventType"];
            created?: components["schemas"]["CreateSemesterEventRequest"][];
            updated?: components["schemas"]["UpdateSemesterEventRequest"][];
        };
        /** @enum {string} */
        SemesterEventType: "SURVEY" | "EVENT";
        UpdateSemesterEventRequest: {
            /** Format: int64 */
            id: number;
            name: string;
        };
        /** @enum {string} */
        ActivityStatus: "ACTIVE" | "COMPLETED" | "WITHDRAWN" | "ENDED" | "DROPOUT";
        CreateMemberSupportersRequest: {
            name: string;
            phoneNumber: string;
            email: string;
            memberType: components["schemas"]["MemberType"];
            jobFamily: components["schemas"]["JobFamily"];
            recruitTypeDetail: components["schemas"]["RecruitTypeDetail"];
            activityStatus: components["schemas"]["ActivityStatus"];
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
            activityCertNumber?: string;
            memo?: string;
        };
        /** @enum {string} */
        MemberType: "SEMESTER" | "MAKERS" | "SUPPORTERS";
        /** @enum {string} */
        RecruitTypeDetail: "REGULAR" | "NEW" | "REFILL";
        /** @enum {string} */
        CareerDetails: "STUDENT" | "EXPECTED_GRADUATE" | "JOB_SEEKER" | "BETWEEN_JOBS" | "EMPLOYEE";
        CreateMemberSemesterRequest: {
            name: string;
            email: string;
            phoneNumber: string;
            jobFamily: components["schemas"]["JobFamily"];
            recruitTypeDetail: components["schemas"]["RecruitTypeDetail"];
            activityStatus: components["schemas"]["ActivityStatus"];
            careerDetails: components["schemas"]["CareerDetails"];
            /** Format: int64 */
            semesterId: number;
            /** Format: int64 */
            teamId?: number;
            experiencePeriod?: components["schemas"]["ExperiencePeriod"];
            memo?: string;
            interestedDomains?: string[];
            region?: components["schemas"]["Region"];
        };
        /** @enum {string} */
        ExperiencePeriod: "NONE" | "ONE_TO_TWO" | "THREE_TO_FOUR" | "FIVE_PLUS";
        /** @enum {string} */
        Region: "SEOUL" | "GYEONGGI" | "INCHEON" | "BUSAN" | "DAEGU" | "DAEJEON" | "GWANGJU" | "ULSAN" | "SEJONG" | "GANGWON" | "CHUNGBUK" | "CHUNGNAM" | "JEONBUK" | "JEONNAM" | "GYEONGBUK" | "GYEONGNAM" | "JEJU" | "OVERSEAS";
        /** @enum {string} */
        Availability: "UNAVAILABLE" | "CONSIDER_LATER" | "AVAILABLE_BY_TOPIC" | "HIGHLY_AVAILABLE";
        /** @enum {string} */
        CareerLevel: "UNDER_1_YEAR" | "JUNIOR" | "MIDDLE" | "SENIOR";
        CreateMemberMakersRequest: {
            name: string;
            email: string;
            phoneNumber: string;
            jobFamily: components["schemas"]["JobFamily"];
            careerDetails: components["schemas"]["CareerDetails"];
            makersTeam: components["schemas"]["MakersTeam"];
            recruitTypeDetail: components["schemas"]["RecruitTypeDetail"];
            activityStatus: components["schemas"]["ActivityStatus"];
            region?: components["schemas"]["Region"];
            interestedDomains?: string[];
            experiencePeriod?: components["schemas"]["ExperiencePeriod"];
            mentoringAvailability?: components["schemas"]["Availability"];
            projectSupplementAvailability?: components["schemas"]["Availability"];
            speakerAvailability?: components["schemas"]["Availability"];
            careerLevel?: components["schemas"]["CareerLevel"];
            skills?: string;
            company?: string;
            expertTopics?: string;
            activityCertNumber?: string;
            memo?: string;
        };
        /** @enum {string} */
        MakersTeam: "TEAM_1" | "TEAM_2";
        PreviewMailRequest: {
            /** Format: int64 */
            scenarioId: number;
            /** Format: int64 */
            applyId: number;
            inputVariables: {
                [key: string]: string;
            };
        };
        MailPreviewResponse: {
            /** Format: int64 */
            scenarioId?: number;
            /** Format: int64 */
            applyId?: number;
            receiverEmail?: string;
            subject?: string;
            body?: string;
        };
        SendMailDispatchRequest: {
            /** Format: int64 */
            recruitId: number;
            /** Format: int64 */
            scenarioId: number;
            applyIds: number[];
            subjectOverride?: string;
            inputVariables?: {
                [key: string]: string;
            };
        };
        /** @enum {string} */
        MailDispatchJobStatus: "REQUESTED" | "PROCESSING" | "COMPLETED" | "FAILED";
        MailDispatchResponse: {
            /** Format: int64 */
            dispatchJobId?: number;
            status?: components["schemas"]["MailDispatchJobStatus"];
            /** Format: int32 */
            targetCount?: number;
            /** Format: int32 */
            processingCount?: number;
            /** Format: int32 */
            successCount?: number;
            /** Format: int32 */
            failedCount?: number;
        };
        /** @enum {string} */
        EmailTemplate: "AUTH_CODE" | "PIN_RESET" | "REMIND_APPLY";
        SendManualTemplatedEmailRequest: {
            sendGroupCode?: components["schemas"]["EmailTemplate"];
            to?: string;
            content?: {
                [key: string]: string;
            };
        };
        SendManualBulkTemplatedEmailRequest: {
            sendGroupCode?: components["schemas"]["EmailTemplate"];
            toList?: string[];
            content?: {
                [key: string]: string;
            };
        };
        ApplyPassRequest: {
            applyIds?: number[];
        };
        /** @description 관리자 계정 생성 요청 */
        AdminAccountCreateRequest: {
            /**
             * @description 관리자 계정 이메일
             * @example admin@ject.kr
             */
            email: string;
            /**
             * @description 관리자 계정 비밀번호
             * @example password123
             */
            password: string;
            /**
             * @description 관리자 이름
             * @example 김젝트
             */
            name?: string | null;
            role: components["schemas"]["Role"];
        };
        /**
         * @description 관리자 계정 유형
         * @example OPERATIONS
         * @enum {string}
         */
        Role: "ADMIN" | "OPERATIONS" | "SUPPORTER" | "SEMESTER" | "APPLY" | "VERIFICATION" | "ADMIN" | "OPERATIONS" | "SUPPORTER";
        AdminLoginRequest: {
            email: string;
            password: string;
        };
        /** @description 운영 서포터즈 구성원 수정 요청. 전달하지 않은 항목은 기존 값 유지 */
        UpdateMemberSupportersRequest: {
            /**
             * @description 이름
             * @example 김젝트
             */
            name?: string | null;
            /**
             * @description 전화번호
             * @example 01012345678
             */
            phoneNumber?: string | null;
            /**
             * @description 이메일
             * @example supporter@ject.kr
             */
            email?: string | null;
            jobFamily?: components["schemas"]["JobFamily"];
            recruitTypeDetail?: components["schemas"]["RecruitTypeDetail"];
            activityStatus?: components["schemas"]["ActivityStatus"];
            /**
             * Format: date
             * @description 활동 시작일
             * @example 2026-01-01
             */
            startDate?: string | null;
            /**
             * Format: date
             * @description 활동 종료일
             * @example 2026-12-31
             */
            endDate?: string | null;
            /**
             * @description 활동 증명서 번호
             * @example JECT-SUPPORTERS-001
             */
            activityCertNumber?: string | null;
            /**
             * @description 비고
             * @example 차기 활동 참여 희망
             */
            memo?: string | null;
        };
        /** @description 일반 구성원 편집 요청. 전달하지 않은 항목은 기존 값 유지 */
        EditMemberSemesterRequest: {
            /**
             * @description 이름
             * @example 김젝트
             */
            name?: string | null;
            /**
             * @description 이메일
             * @example member@ject.kr
             */
            email?: string | null;
            /**
             * @description 전화번호
             * @example 01012345678
             */
            phoneNumber?: string | null;
            jobFamily?: components["schemas"]["JobFamily"];
            recruitTypeDetail?: components["schemas"]["RecruitTypeDetail"];
            activityStatus?: components["schemas"]["ActivityStatus"];
            careerDetails?: components["schemas"]["CareerDetails"];
            /**
             * Format: int64
             * @description 기수 ID. 전달하면 팀 소속도 함께 편집
             * @example 2
             */
            semesterId?: number | null;
            /**
             * Format: int64
             * @description 팀 ID. 단독 전달 시 현재 기수의 팀으로 편집
             * @example 5
             */
            teamId?: number | null;
            experiencePeriod?: components["schemas"]["ExperiencePeriod"];
            /**
             * @description 비고
             * @example 일반 구성원 비고
             */
            memo?: string | null;
            /**
             * @description 관심 도메인 목록(1~3개)
             * @example [
             *       "커머스",
             *       "핀테크"
             *     ]
             */
            interestedDomains?: (string | null)[] | null;
            region?: components["schemas"]["Region"];
            /**
             * @description 활동 증명서 번호
             * @example JECT-SEMESTER-001
             */
            certNumber?: string | null;
            /**
             * @description 1차 활동 리뷰
             * @example https://example.com/review/1
             */
            firstReview?: string | null;
            /**
             * @description 2차 활동 리뷰
             * @example https://example.com/review/2
             */
            secondReview?: string | null;
        };
        /** @description 일반 구성원 행사 참여 상태 수정 요청 */
        EditEventParticipationRequest: {
            /**
             * Format: int64
             * @description 기수별 행사 ID
             * @example 1
             */
            semesterEventId: number;
            participationStatus?: components["schemas"]["ParticipationStatus"];
        };
        /**
         * @description 행사 참여 상태. null이면 미지정 처리
         * @example ATTENDED
         * @enum {string|null}
         */
        ParticipationStatus: "ATTENDED" | "ABSENT" | "ATTENDED" | "ABSENT" | null;
        /** @description 메이커스팀 구성원 수정 요청. 전달하지 않은 항목은 기존 값 유지 */
        UpdateMemberMakersRequest: {
            /**
             * @description 이름
             * @example 김젝트
             */
            name?: string | null;
            /**
             * @description 이메일
             * @example member@ject.kr
             */
            email?: string | null;
            /**
             * @description 전화번호
             * @example 01012345678
             */
            phoneNumber?: string | null;
            jobFamily?: components["schemas"]["JobFamily"];
            careerDetails?: components["schemas"]["CareerDetails"];
            makersTeam?: components["schemas"]["MakersTeam"];
            recruitTypeDetail?: components["schemas"]["RecruitTypeDetail"];
            activityStatus?: components["schemas"]["ActivityStatus"];
            region?: components["schemas"]["Region"];
            /**
             * @description 관심 도메인 목록(1~3개)
             * @example [
             *       "커머스",
             *       "핀테크"
             *     ]
             */
            interestedDomains?: (string | null)[] | null;
            experiencePeriod?: components["schemas"]["ExperiencePeriod"];
            mentoringAvailability?: components["schemas"]["Availability"];
            projectSupplementAvailability?: components["schemas"]["Availability"];
            speakerAvailability?: components["schemas"]["Availability"];
            careerLevel?: components["schemas"]["CareerLevel"];
            /**
             * @description 보유 기술
             * @example Java, Spring
             */
            skills?: string | null;
            /**
             * @description 회사
             * @example 젝트
             */
            company?: string | null;
            /**
             * @description 공유 가능한 전문 주제
             * @example Spring 성능 최적화
             */
            expertTopics?: string | null;
            /**
             * @description 활동 증명서 번호
             * @example JECT-MAKERS-001
             */
            activityCertNumber?: string | null;
            /**
             * @description 비고
             * @example 차기 프로젝트 참여 희망
             */
            memo?: string | null;
        };
        /**
         * @description 선정 결과
         * @example PASSED
         * @enum {string}
         */
        SelectionResult: "UNDECIDED" | "PASSED" | "WAITLISTED" | "FAILED";
        /** @description 지원서별 선정 결과 */
        SelectionResultItem: {
            /**
             * Format: int64
             * @description 지원서 ID
             * @example 1
             */
            applyId: number;
            selectionResult: components["schemas"]["SelectionResult"];
            /**
             * Format: int32
             * @description 예비 번호. 예비 합격일 때만 입력
             * @example 1
             */
            waitlistNumber?: number | null;
        };
        /** @description 지원서 선정 결과 일괄 변경 요청 */
        SelectionResultUpdateRequest: {
            /**
             * Format: int64
             * @description 모집 공고 ID
             * @example 1
             */
            recruitId: number;
            /** @description 지원서별 선정 결과 */
            selectionResults: components["schemas"]["SelectionResultItem"][];
        };
        /** @description 관리자 계정 정보 수정 요청 */
        AdminAccountUpdateRequest: {
            /**
             * @description 관리자 이름
             * @example 김젝트
             */
            name?: string | null;
            role: components["schemas"]["Role"];
            /**
             * @description 관리자 계정 활성화 여부
             * @example true
             */
            active: boolean;
        };
        /** @description 관리자 계정 권한 수정 요청 */
        AdminAccountRoleUpdateRequest: {
            role: components["schemas"]["Role"];
        };
        /** @description 관리자 계정 활성화 상태 수정 요청 */
        AdminAccountActiveUpdateRequest: {
            /**
             * @description 관리자 계정 활성화 여부
             * @example true
             */
            active: boolean;
        };
        /** @description 관리자 계정 일괄 비활성화 요청 */
        AdminAccountBulkDeactivateRequest: {
            /**
             * Format: int64
             * @description 비활성화할 관리자 계정 ID
             * @example 1
             */
            memberId: number;
        };
        SemesterEventResponse: {
            /** Format: int64 */
            id?: number;
            name?: string;
        };
        SemesterEventsResponse: {
            type?: components["schemas"]["SemesterEventType"];
            events?: components["schemas"]["SemesterEventResponse"][];
        };
        CursorPageResponseMemberSupportersListResponse: {
            content?: components["schemas"]["MemberSupportersListResponse"][];
            /** Format: int32 */
            size?: number;
            hasNext?: boolean;
            /** Format: int64 */
            nextCursor?: number;
            /** Format: int64 */
            totalCount?: number;
        };
        MemberSupportersListResponse: {
            /** Format: int64 */
            memberActivityId?: number;
            name?: string;
            phoneNumber?: string;
            jobFamily?: components["schemas"]["JobFamily"];
            recruitTypeDetail?: components["schemas"]["RecruitTypeDetail"];
            activityStatus?: components["schemas"]["ActivityStatus"];
            memo?: string;
        };
        MemberSupportersDetailResponse: {
            /** Format: int64 */
            memberActivityId?: number;
            name?: string;
            phoneNumber?: string;
            email?: string;
            memberType?: components["schemas"]["MemberType"];
            jobFamily?: components["schemas"]["JobFamily"];
            recruitTypeDetail?: components["schemas"]["RecruitTypeDetail"];
            activityStatus?: components["schemas"]["ActivityStatus"];
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
            activityCertNumber?: string;
            memo?: string;
        };
        CursorPageResponseSearchMemberSemesterResponse: {
            content?: components["schemas"]["SearchMemberSemesterResponse"][];
            /** Format: int32 */
            size?: number;
            hasNext?: boolean;
            /** Format: int64 */
            nextCursor?: number;
            /** Format: int64 */
            totalCount?: number;
        };
        SearchMemberSemesterResponse: {
            /** Format: int64 */
            memberActivityId?: number;
            name?: string;
            jobFamily?: components["schemas"]["JobFamily"];
            phoneNumber?: string;
            careerDetails?: components["schemas"]["CareerDetails"];
            experiencePeriod?: components["schemas"]["ExperiencePeriod"];
            status?: components["schemas"]["ActivityStatus"];
        };
        EventParticipationResponse: {
            /** Format: int64 */
            semesterEventId?: number;
            name?: string;
            participationStatus?: components["schemas"]["ParticipationStatus"];
        };
        MemberSemesterResponse: {
            /** Format: int64 */
            memberActivityId?: number;
            name?: string;
            email?: string;
            phoneNumber?: string;
            region?: components["schemas"]["Region"];
            interestedDomains?: string[];
            jobFamily?: components["schemas"]["JobFamily"];
            recruitTypeDetail?: components["schemas"]["RecruitTypeDetail"];
            careerDetails?: components["schemas"]["CareerDetails"];
            activityStatus?: components["schemas"]["ActivityStatus"];
            experiencePeriod?: components["schemas"]["ExperiencePeriod"];
            memo?: string;
            semester?: components["schemas"]["Semester"];
            team?: components["schemas"]["Team"];
            certNumber?: string;
            firstReview?: string;
            secondReview?: string;
            events?: components["schemas"]["EventParticipationResponse"][];
            surveys?: components["schemas"]["EventParticipationResponse"][];
        };
        Semester: {
            /** Format: int64 */
            semesterId?: number;
            semesterName?: string;
        };
        Team: {
            /** Format: int64 */
            teamId?: number;
            teamName?: string;
        };
        CursorPageResponseMemberMakersListResponse: {
            content?: components["schemas"]["MemberMakersListResponse"][];
            /** Format: int32 */
            size?: number;
            hasNext?: boolean;
            /** Format: int64 */
            nextCursor?: number;
            /** Format: int64 */
            totalCount?: number;
        };
        MemberMakersListResponse: {
            /** Format: int64 */
            memberActivityId?: number;
            name?: string;
            email?: string;
            phoneNumber?: string;
            jobFamily?: components["schemas"]["JobFamily"];
            makersTeam?: components["schemas"]["MakersTeam"];
            recruitTypeDetail?: components["schemas"]["RecruitTypeDetail"];
            activityStatus?: components["schemas"]["ActivityStatus"];
            memo?: string;
        };
        MemberMakersDetailResponse: {
            /** Format: int64 */
            memberActivityId?: number;
            name?: string;
            email?: string;
            phoneNumber?: string;
            jobFamily?: components["schemas"]["JobFamily"];
            careerDetails?: components["schemas"]["CareerDetails"];
            makersTeam?: components["schemas"]["MakersTeam"];
            recruitTypeDetail?: components["schemas"]["RecruitTypeDetail"];
            region?: components["schemas"]["Region"];
            interestedDomains?: string[];
            experiencePeriod?: components["schemas"]["ExperiencePeriod"];
            mentoringAvailability?: components["schemas"]["Availability"];
            projectSupplementAvailability?: components["schemas"]["Availability"];
            speakerAvailability?: components["schemas"]["Availability"];
            careerLevel?: components["schemas"]["CareerLevel"];
            activityStatus?: components["schemas"]["ActivityStatus"];
            skills?: string;
            company?: string;
            expertTopics?: string;
            activityCertNumber?: string;
            memo?: string;
        };
        /**
         * @description 선정 결과 필터
         * @example PASSED
         * @enum {string|null}
         */
        MailTargetSelectionResult: "PASSED" | "WAITLISTED" | "FAILED" | null;
        MailTargetResponse: {
            /** Format: int64 */
            applyId?: number;
            name?: string;
            phoneNumber?: string;
            email?: string;
            selectionResult?: components["schemas"]["SelectionResult"];
            /** Format: int32 */
            waitlistNumber?: number;
        };
        Pageable: {
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            sort?: string[];
        };
        PageMailScenarioResponse: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["MailScenarioResponse"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            /** Format: int32 */
            numberOfElements?: number;
            pageable?: components["schemas"]["PageableObject"];
            empty?: boolean;
        };
        PageableObject: {
            /** Format: int64 */
            offset?: number;
            sort?: components["schemas"]["SortObject"];
            paged?: boolean;
            /** Format: int32 */
            pageNumber?: number;
            /** Format: int32 */
            pageSize?: number;
            unpaged?: boolean;
        };
        SortObject: {
            empty?: boolean;
            sorted?: boolean;
            unsorted?: boolean;
        };
        MailScenarioVariableResponse: {
            /** Format: int64 */
            scenarioId?: number;
            name?: string;
            customVariables?: components["schemas"]["CustomVariableResponse"][];
            personalVariables?: string[];
        };
        MailRecruitResponse: {
            /**
             * Format: int64
             * @description 모집 공고 ID
             * @example 1
             */
            recruitId?: number;
            /**
             * Format: int64
             * @description 기수 ID
             * @example 2
             */
            semesterId?: number;
            /**
             * @description 기수명
             * @example 10기
             */
            semesterName?: string;
            jobFamily?: components["schemas"]["JobFamily"];
            /**
             * @description 직군 표시명
             * @example 백엔드 개발자(BE)
             */
            jobFamilyDescription?: string;
            recruitType?: components["schemas"]["RecruitType"];
            /**
             * @description 모집 유형 표시명
             * @example 정규 기수 모집
             */
            recruitTypeDescription?: string;
            recruitTypeDetail?: components["schemas"]["RecruitTypeDetail"];
            /**
             * @description 모집 세부 유형 표시명
             * @example 정규 모집
             */
            recruitTypeDetailDescription?: string;
            /**
             * Format: date-time
             * @description 모집 시작일
             */
            startDate?: string;
            /**
             * Format: date-time
             * @description 모집 종료일
             */
            endDate?: string;
            /**
             * Format: date-time
             * @description 등록일
             */
            createdAt?: string;
        };
        /**
         * @description 모집 유형
         * @example SEMESTER
         * @enum {string}
         */
        RecruitType: "SEMESTER" | "MAKERS" | "SUPPORTERS" | "REGULAR" | "REGULAR_WAITLIST" | "BACKFILL" | "MANUAL";
        /** @enum {string} */
        ApplyStatus: "JOINED" | "TEMP_SAVED" | "SUBMITTED" | "REJECTED";
        AdminApplyResponse: {
            /** Format: int64 */
            applyId?: number;
            name?: string;
            phoneNumber?: string;
            email?: string;
            jobFamily?: components["schemas"]["JobFamily"];
            careerDetails?: string;
            recruitType?: string;
            note?: string;
        };
        PageAdminApplyResponse: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["AdminApplyResponse"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            /** Format: int32 */
            numberOfElements?: number;
            pageable?: components["schemas"]["PageableObject"];
            empty?: boolean;
        };
        AdminApplyDetailResponse: {
            /** Format: int64 */
            applyId?: number;
            name?: string;
            phoneNumber?: string;
            email?: string;
            jobFamily?: components["schemas"]["JobFamily"];
            careerDetails?: string;
            recruitType?: string;
            note?: string;
            region?: string;
            experiencePeriod?: string;
            interestedDomains?: string[];
            answers?: {
                [key: string]: string;
            };
            portfolios?: components["schemas"]["ApplyPortfolioDto"][];
        };
        /** @enum {string} */
        MemberStatus: "ACTIVE" | "LOCKED";
        AdminAccountResponse: {
            /** Format: int64 */
            id?: number;
            email?: string;
            name?: string;
            role?: components["schemas"]["Role"];
            status?: components["schemas"]["MemberStatus"];
        };
        PageAdminAccountResponse: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["AdminAccountResponse"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            /** Format: int32 */
            numberOfElements?: number;
            pageable?: components["schemas"]["PageableObject"];
            empty?: boolean;
        };
        /** @description 구성원 일괄 삭제 요청 */
        DeleteMembersRequest: {
            /**
             * @description 삭제할 구성원 활동 ID 목록
             * @example [
             *       1,
             *       2,
             *       3
             *     ]
             */
            memberActivityIds: number[];
        };
        /** @description 지원서 일괄 삭제 요청 */
        SubmittedApplyBulkDeleteRequest: {
            /**
             * @description 삭제할 지원서 ID 목록
             * @example [
             *       1,
             *       2,
             *       3
             *     ]
             */
            applyIds: number[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    updateRecruit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recruitId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecruitUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cancelRecruit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recruitId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateRecruit_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recruitId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecruitUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateScenario: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenarioId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MailScenarioRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MailScenarioResponse"];
                };
            };
        };
    };
    deleteScenario: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenarioId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    findApply: {
        parameters: {
            query?: {
                applyStatus?: components["schemas"]["ApplyStatus"];
            };
            header?: never;
            path: {
                applyId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminApplyDetailResponse"];
                };
            };
        };
    };
    editSubmittedApply: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applyId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmittedApplyEditRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteApply: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applyId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SemesterRegisterRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getEvents: {
        parameters: {
            query: {
                type: components["schemas"]["SemesterEventType"];
            };
            header?: never;
            path: {
                semesterId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SemesterEventsResponse"];
                };
            };
        };
    };
    editEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                semesterId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditSemesterEventsRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    registerRecruit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecruitRegisterRequest"][];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAdminMemberSupportersList: {
        parameters: {
            query?: {
                cursor?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CursorPageResponseMemberSupportersListResponse"];
                };
            };
        };
    };
    createAdminMemberSupporters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMemberSupportersRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteAdminMemberSupportersList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteMembersRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    searchAdminMemberSemesterList: {
        parameters: {
            query?: {
                cursor?: number;
                size?: number;
                semesterId?: number;
                jobFamily?: components["schemas"]["JobFamily"];
                recruitTypeDetail?: components["schemas"]["RecruitTypeDetail"];
                careerDetails?: components["schemas"]["CareerDetails"];
                teamId?: number;
                status?: components["schemas"]["ActivityStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CursorPageResponseSearchMemberSemesterResponse"];
                };
            };
        };
    };
    createAdminMemberSemester: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMemberSemesterRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteAdminMemberSemesterList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteMembersRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAdminMemberMakersList: {
        parameters: {
            query?: {
                cursor?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CursorPageResponseMemberMakersListResponse"];
                };
            };
        };
    };
    createAdminMemberMakers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMemberMakersRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteAdminMemberMakersList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteMembersRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    searchScenarios: {
        parameters: {
            query: {
                category?: components["schemas"]["MailScenarioCategory"];
                type?: components["schemas"]["MailScenarioType"];
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageMailScenarioResponse"];
                };
            };
        };
    };
    createScenario: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MailScenarioRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MailScenarioResponse"];
                };
            };
        };
    };
    preview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreviewMailRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MailPreviewResponse"];
                };
            };
        };
    };
    sendMail: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMailDispatchRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MailDispatchResponse"];
                };
            };
        };
    };
    sendManualTemplatedEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendManualTemplatedEmailRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    sendManualBulkTemplatedEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendManualBulkTemplatedEmailRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    passApply: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplyPassRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": number;
                };
            };
        };
    };
    findAccounts: {
        parameters: {
            query: {
                roles?: components["schemas"]["Role"][];
                statuses?: components["schemas"]["MemberStatus"][];
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageAdminAccountResponse"];
                };
            };
        };
    };
    createAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminAccountCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logoutAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    loginAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminLoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": boolean;
                };
            };
        };
    };
    getAdminMemberSupportersDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memberActivityId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MemberSupportersDetailResponse"];
                };
            };
        };
    };
    deleteAdminMemberSupporters: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memberActivityId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    editAdminMemberSupporters: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memberActivityId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMemberSupportersRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMemberSemester: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memberActivityId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MemberSemesterResponse"];
                };
            };
        };
    };
    deleteAdminMemberSemester: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memberActivityId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    editAdminMemberSemester: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memberActivityId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditMemberSemesterRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    editEventParticipation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memberActivityId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditEventParticipationRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAdminMemberMakersDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memberActivityId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MemberMakersDetailResponse"];
                };
            };
        };
    };
    deleteAdminMemberMakers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memberActivityId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    editAdminMemberMakers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memberActivityId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMemberMakersRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateSelectionResults: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SelectionResultUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": number;
                };
            };
        };
    };
    updateAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memberId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminAccountUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memberId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminAccountRoleUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateActive: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memberId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminAccountActiveUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deactivateAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminAccountBulkDeactivateRequest"][];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    searchTargets: {
        parameters: {
            query: {
                /**
                 * @description 모집 공고 ID
                 * @example 1
                 */
                recruitId: number;
                /**
                 * @description 선정 결과 필터
                 * @example PASSED
                 */
                selectionResult?: components["schemas"]["MailTargetSelectionResult"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MailTargetResponse"][];
                };
            };
        };
    };
    getVariablesByScenario: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenarioId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MailScenarioVariableResponse"];
                };
            };
        };
    };
    getRecruits: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MailRecruitResponse"][];
                };
            };
        };
    };
    findApplies: {
        parameters: {
            query: {
                applyStatus?: components["schemas"]["ApplyStatus"];
                semesterId?: number;
                jobFamily?: components["schemas"]["JobFamily"];
                recruitType?: components["schemas"]["RecruitType"];
                recruitTypeDetail?: components["schemas"]["RecruitTypeDetail"];
                recruitId?: number;
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageAdminApplyResponse"];
                };
            };
        };
    };
    deleteSubmittedApplies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmittedApplyBulkDeleteRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": number;
                };
            };
        };
    };
    deleteEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                semesterId: number;
                semesterEventId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
