/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/recruits/{recruitId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 모집 수정
         * @description 모집 정보를 수정합니다.
         */
        put: operations["updateRecruit"];
        post?: never;
        /**
         * 모집 취소
         * @description 모집 정보를 제거합니다.
         */
        delete: operations["cancelRecruit"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/recruits/{recruitId}/force-update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 모집 정보 강제 수정
         * @description 마감 여부와 관계없이 모집 정보를 강제로 수정합니다.
         */
        put: operations["updateRecruit_1"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/mails/scenarios/{scenarioId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 시나리오 수정
         * @description 기존 메일 발송 시나리오를 수정합니다.
         */
        put: operations["updateScenario"];
        post?: never;
        /**
         * 시나리오 삭제
         * @description 메일 발송 시나리오를 삭제합니다.
         */
        delete: operations["deleteScenario"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/applies/{applyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 지원서 상세 조회
         * @description 전달한 ID에 해당하는 지원서의 상세 정보를 조회합니다.
         */
        get: operations["findApply"];
        /**
         * 제출된 지원서 수정
         * @description 전달한 ID에 해당하는 제출된 지원서의 정보를 수정 합니다.
         */
        put: operations["editSubmittedApply"];
        post?: never;
        /**
         * 지원서 삭제
         * @description 전달한 ID에 해당하는 지원서를 삭제합니다.
         */
        delete: operations["deleteApply"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/semesters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 기수 등록
         * @description 새로운 기수를 등록합니다.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/semesters/{semesterId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 기수별 행사 목록 조회
         * @description 선택한 기수와 행사 타입의 행사 목록을 조회합니다.
         */
        get: operations["getEvents"];
        put?: never;
        /**
         * 기수별 행사 일괄 편집
         * @description 선택한 기수의 행사 추가와 이름 수정을 원자적으로 처리합니다.
         */
        post: operations["editEvents"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/recruits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 모집 등록
         * @description 모집 정보를 등록합니다.
         */
        post: operations["registerRecruit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/members/supporters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 운영 서포터즈 구성원 목록 조회
         * @description 운영 서포터즈 구성원 목록을 조회합니다.
         */
        get: operations["getAdminMemberSupportersList"];
        put?: never;
        /**
         * 운영 서포터즈 구성원 추가
         * @description 운영 서포터즈 구성원을 추가합니다.
         */
        post: operations["createAdminMemberSupporters"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/members/semester": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 일반 구성원 리스트 조회
         * @description 일반 구성원 목록을 커서기반 페이징과 필터를 적용해 조회합니다.
         */
        get: operations["searchAdminMemberSemesterList"];
        put?: never;
        /**
         * 일반 구성원 추가
         * @description 일반 구성원을 추가합니다.
         */
        post: operations["createAdminMemberSemester"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/members/makers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 메이커스팀 구성원 목록 조회
         * @description 메이커스팀 구성원 목록을 조회합니다.
         */
        get: operations["getAdminMemberMakersList"];
        put?: never;
        /**
         * 메이커스팀 구성원 추가
         * @description 메이커스팀 구성원을 추가합니다.
         */
        post: operations["createAdminMemberMakers"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/mails/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 시나리오 목록 조회
         * @description 등록된 모든 메일 발송 시나리오를 조회합니다.
         */
        get: operations["getScenarios"];
        put?: never;
        /**
         * 시나리오 생성
         * @description 새로운 메일 발송 시나리오를 생성합니다.
         */
        post: operations["createScenario"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/emails/send/manual": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 템플릿 이메일 단건 발송
         * @description 선택된 템플릿으로 단건 이메일을 발송합니다.
         */
        post: operations["sendManualTemplatedEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/emails/send/manual/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 템플릿 이메일 일괄 발송
         * @description 선택된 템플릿으로 여러 이메일을 발송합니다.
         */
        post: operations["sendManualBulkTemplatedEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/apply/pass": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 지원자 합격
         * @description 지원자를 합격 처리하여 구성원으로 승인합니다.
         */
        post: operations["passApply"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 관리자 계정 목록 조회
         * @description 관리자 계정 목록을 조회합니다. 계정 유형과 상태를 복수 필터로 선택할 수 있습니다.
         */
        get: operations["findAccounts"];
        put?: never;
        /**
         * 관리자 계정 생성
         * @description 관리자 계정 유형의 계정을 생성합니다.
         */
        post: operations["createAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin-auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 관리자 로그아웃
         * @description 관리자가 로그아웃합니다.
         */
        post: operations["logoutAdmin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin-auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 관리자 로그인
         * @description 관리자 로그인을 시도합니다.
         */
        post: operations["loginAdmin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/accounts/{memberId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 관리자 계정 정보 수정
         * @description 관리자 계정의 이메일, 이름, 권한, 활성화 상태를 수정합니다.
         */
        patch: operations["updateAccount"];
        trace?: never;
    };
    "/admin/accounts/{memberId}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 관리자 계정 권한 수정
         * @description 관리자 계정의 권한을 수정합니다.
         */
        patch: operations["updateRole"];
        trace?: never;
    };
    "/admin/accounts/{memberId}/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 관리자 계정 활성화 상태 수정
         * @description 관리자 계정을 활성화하거나 비활성화합니다.
         */
        patch: operations["updateActive"];
        trace?: never;
    };
    "/admin/accounts/members/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 관리자 계정 일괄 비활성화
         * @description 요청한 관리자 계정을 일괄 비활성화합니다. 활성화는 단건 API를 사용합니다.
         */
        patch: operations["deactivateAccounts"];
        trace?: never;
    };
    "/admin/members/supporters/{memberActivityId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 운영 서포터즈 구성원 상세 조회
         * @description 운영 서포터즈 구성원을 상세 조회합니다.
         */
        get: operations["getAdminMemberSupportersDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/members/makers/{memberActivityId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 메이커스팀 구성원 상세 조회
         * @description 메이커스팀 구성원을 상세 조회합니다.
         */
        get: operations["getAdminMemberMakersDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/mails/scenarios/{scenarioId}/variables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 시나리오 변수 목록 조회
         * @description 시나리오 ID로 템플릿 변수 목록(공통/개인)을 조회합니다.
         */
        get: operations["getVariablesByScenario"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/applies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 지원서 목록 조회
         * @description 지원서들의 목록을 조회합니다. 모집 공고, 모집 유형, 모집 사유, 기수, 직군, 지원 상태로 필터링할 수 있습니다.
         */
        get: operations["findApplies"];
        put?: never;
        post?: never;
        /**
         * 지원서 다수 삭제
         * @description 선택한 다수의 지원서들을 삭제합니다. 삭제한 수를 반환합니다.
         */
        delete: operations["deleteSubmittedApplies"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        JobFamily: "PM" | "PD" | "FE" | "BE" | "APP" | "SUPPORTER" | "OPS" | "INFRA" | "BX" | "ER";
        RecruitUpdateRequest: {
            jobFamily: components["schemas"]["JobFamily"];
            /** Format: date-time */
            startDate: string;
            /** Format: date-time */
            endDate: string;
        };
        CustomVariableRequest: {
            key: string;
            label: string;
            inputType: components["schemas"]["VariableInputType"];
            required?: boolean;
            description?: string;
        };
        /** @enum {string} */
        MailScenarioCategory: "GENERAL" | "CLUB_MEMBER" | "MAKERS" | "SUPPORTERS";
        MailScenarioRequest: {
            name: string;
            category: components["schemas"]["MailScenarioCategory"];
            type: components["schemas"]["MailScenarioType"];
            scenarioCode: string;
            subjectTemplate: string;
            bodyTemplate: string;
            active: boolean;
            customVariables: components["schemas"]["CustomVariableRequest"][];
        };
        /** @enum {string} */
        MailScenarioType: "FIRST_PASS" | "FINAL_PASS" | "STANDBY_PASS" | "REJECT" | "ETC";
        /** @enum {string} */
        VariableInputType: "TEXT" | "URL" | "EMAIL" | "PHONE";
        CustomVariableResponse: {
            key?: string;
            label?: string;
            inputType?: string;
            required?: boolean;
            description?: string;
        };
        MailScenarioResponse: {
            /** Format: int64 */
            id?: number;
            name?: string;
            category?: components["schemas"]["MailScenarioCategory"];
            type?: components["schemas"]["MailScenarioType"];
            scenarioCode?: string;
            subjectTemplate?: string;
            bodyTemplate?: string;
            active?: boolean;
            /** Format: date-time */
            createdAt?: string;
            customVariables?: components["schemas"]["CustomVariableResponse"][];
        };
        ApplyPortfolioDto: {
            fileUrl?: string;
            fileName?: string;
            fileSize?: string;
            sequence?: string;
        };
        SubmittedApplyEditRequest: {
            name: string;
            phoneNumber: string;
            email: string;
            jobFamily: components["schemas"]["JobFamily"];
            answers: {
                [key: string]: string;
            };
            portfolios?: components["schemas"]["ApplyPortfolioDto"][];
        };
        RecruitRegisterRequest: {
            jobFamily: components["schemas"]["JobFamily"];
            /** Format: date-time */
            startDate: string;
            /** Format: date-time */
            endDate: string;
        };
        SemesterRegisterRequest: {
            name?: string;
            recruitRegisterRequests?: components["schemas"]["RecruitRegisterRequest"][];
        };
        CreateSemesterEventRequest: {
            name: string;
        };
        EditSemesterEventsRequest: {
            type: components["schemas"]["SemesterEventType"];
            created?: components["schemas"]["CreateSemesterEventRequest"][];
            updated?: components["schemas"]["UpdateSemesterEventRequest"][];
        };
        /** @enum {string} */
        SemesterEventType: "SURVEY" | "EVENT";
        UpdateSemesterEventRequest: {
            /** Format: int64 */
            id: number;
            name: string;
        };
        /** @enum {string} */
        ActivityStatus: "ACTIVE" | "COMPLETED" | "WITHDRAWN" | "ENDED" | "DROPOUT";
        CreateMemberSupportersRequest: {
            name: string;
            phoneNumber: string;
            email: string;
            memberType: components["schemas"]["MemberType"];
            jobFamily: components["schemas"]["JobFamily"];
            recruitTypeDetail: components["schemas"]["RecruitTypeDetail"];
            activityStatus: components["schemas"]["ActivityStatus"];
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
            activityCertNumber?: string;
            memo?: string;
        };
        /** @enum {string} */
        MemberType: "SEMESTER" | "MAKERS" | "SUPPORTERS";
        /** @enum {string} */
        RecruitTypeDetail: "REGULAR" | "NEW" | "REFILL";
        /** @enum {string} */
        CareerDetails: "STUDENT" | "EXPECTED_GRADUATE" | "JOB_SEEKER" | "BETWEEN_JOBS" | "EMPLOYEE";
        CreateMemberSemesterRequest: {
            name: string;
            email: string;
            phoneNumber: string;
            jobFamily: components["schemas"]["JobFamily"];
            recruitTypeDetail: components["schemas"]["RecruitTypeDetail"];
            activityStatus: components["schemas"]["ActivityStatus"];
            careerDetails: components["schemas"]["CareerDetails"];
            /** Format: int64 */
            semesterId: number;
            /** Format: int64 */
            teamId?: number;
            experiencePeriod?: components["schemas"]["ExperiencePeriod"];
            memo?: string;
            interestedDomains?: string[];
            region?: components["schemas"]["Region"];
        };
        /** @enum {string} */
        ExperiencePeriod: "NONE" | "ONE_TO_TWO" | "THREE_TO_FOUR" | "FIVE_PLUS";
        /** @enum {string} */
        Region: "SEOUL" | "GYEONGGI" | "INCHEON" | "BUSAN" | "DAEGU" | "DAEJEON" | "GWANGJU" | "ULSAN" | "SEJONG" | "GANGWON" | "CHUNGBUK" | "CHUNGNAM" | "JEONBUK" | "JEONNAM" | "GYEONGBUK" | "GYEONGNAM" | "JEJU" | "OVERSEAS";
        /** @enum {string} */
        Availability: "UNAVAILABLE" | "CONSIDER_LATER" | "AVAILABLE_BY_TOPIC" | "HIGHLY_AVAILABLE";
        /** @enum {string} */
        CareerLevel: "UNDER_1_YEAR" | "JUNIOR" | "MIDDLE" | "SENIOR";
        CreateMemberMakersRequest: {
            name: string;
            email: string;
            phoneNumber: string;
            jobFamily: components["schemas"]["JobFamily"];
            careerDetails: components["schemas"]["CareerDetails"];
            makersTeam: components["schemas"]["MakersTeam"];
            recruitTypeDetail: components["schemas"]["RecruitTypeDetail"];
            activityStatus: components["schemas"]["ActivityStatus"];
            region?: components["schemas"]["Region"];
            interestedDomains?: string[];
            experiencePeriod?: components["schemas"]["ExperiencePeriod"];
            mentoringAvailability?: components["schemas"]["Availability"];
            projectSupplementAvailability?: components["schemas"]["Availability"];
            speakerAvailability?: components["schemas"]["Availability"];
            careerLevel?: components["schemas"]["CareerLevel"];
            skills?: string;
            company?: string;
            expertTopics?: string;
            activityCertNumber?: string;
            memo?: string;
        };
        /** @enum {string} */
        MakersTeam: "TEAM_1" | "TEAM_2";
        /** @enum {string} */
        EmailTemplate: "AUTH_CODE" | "PIN_RESET" | "REMIND_APPLY";
        SendManualTemplatedEmailRequest: {
            sendGroupCode?: components["schemas"]["EmailTemplate"];
            to?: string;
            content?: {
                [key: string]: string;
            };
        };
        SendManualBulkTemplatedEmailRequest: {
            sendGroupCode?: components["schemas"]["EmailTemplate"];
            toList?: string[];
            content?: {
                [key: string]: string;
            };
        };
        ApplyPassRequest: {
            applyIds?: number[];
        };
        /** @description 관리자 계정 생성 요청 */
        AdminAccountCreateRequest: {
            /**
             * @description 관리자 계정 이메일
             * @example admin@ject.kr
             */
            email: string;
            /**
             * @description 관리자 계정 비밀번호
             * @example password123
             */
            password: string;
            /**
             * @description 관리자 이름
             * @example 김젝트
             */
            name?: string | null;
            role: components["schemas"]["Role"];
        };
        /**
         * @description 관리자 계정 유형
         * @example OPERATIONS
         * @enum {string}
         */
        Role: "ADMIN" | "OPERATIONS" | "SUPPORTER" | "SEMESTER" | "APPLY" | "VERIFICATION" | "ADMIN" | "OPERATIONS" | "SUPPORTER";
        AdminLoginRequest: {
            email: string;
            password: string;
        };
        /** @description 관리자 계정 정보 수정 요청 */
        AdminAccountUpdateRequest: {
            /**
             * @description 관리자 이름
             * @example 김젝트
             */
            name?: string | null;
            role: components["schemas"]["Role"];
            /**
             * @description 관리자 계정 활성화 여부
             * @example true
             */
            active: boolean;
        };
        /** @description 관리자 계정 권한 수정 요청 */
        AdminAccountRoleUpdateRequest: {
            role: components["schemas"]["Role"];
        };
        /** @description 관리자 계정 활성화 상태 수정 요청 */
        AdminAccountActiveUpdateRequest: {
            /**
             * @description 관리자 계정 활성화 여부
             * @example true
             */
            active: boolean;
        };
        /** @description 관리자 계정 일괄 비활성화 요청 */
        AdminAccountBulkDeactivateRequest: {
            /**
             * Format: int64
             * @description 비활성화할 관리자 계정 ID
             * @example 1
             */
            memberId: number;
        };
        SemesterEventResponse: {
            /** Format: int64 */
            id?: number;
            name?: string;
        };
        SemesterEventsResponse: {
            type?: components["schemas"]["SemesterEventType"];
            events?: components["schemas"]["SemesterEventResponse"][];
        };
        CursorPageResponseMemberSupportersListResponse: {
            content?: components["schemas"]["MemberSupportersListResponse"][];
            /** Format: int32 */
            size?: number;
            hasNext?: boolean;
            /** Format: int64 */
            nextCursor?: number;
            /** Format: int64 */
            totalCount?: number;
        };
        MemberSupportersListResponse: {
            /** Format: int64 */
            memberActivityId?: number;
            name?: string;
            phoneNumber?: string;
            jobFamily?: components["schemas"]["JobFamily"];
            recruitTypeDetail?: components["schemas"]["RecruitTypeDetail"];
            activityStatus?: components["schemas"]["ActivityStatus"];
            memo?: string;
        };
        MemberSupportersDetailResponse: {
            /** Format: int64 */
            memberActivityId?: number;
            name?: string;
            phoneNumber?: string;
            email?: string;
            memberType?: components["schemas"]["MemberType"];
            jobFamily?: components["schemas"]["JobFamily"];
            recruitTypeDetail?: components["schemas"]["RecruitTypeDetail"];
            activityStatus?: components["schemas"]["ActivityStatus"];
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
            activityCertNumber?: string;
            memo?: string;
        };
        CursorPageResponseSearchMemberSemesterResponse: {
            content?: components["schemas"]["SearchMemberSemesterResponse"][];
            /** Format: int32 */
            size?: number;
            hasNext?: boolean;
            /** Format: int64 */
            nextCursor?: number;
            /** Format: int64 */
            totalCount?: number;
        };
        SearchMemberSemesterResponse: {
            /** Format: int64 */
            memberActivityId?: number;
            name?: string;
            jobFamily?: components["schemas"]["JobFamily"];
            phoneNumber?: string;
            careerDetails?: components["schemas"]["CareerDetails"];
            experiencePeriod?: components["schemas"]["ExperiencePeriod"];
            status?: components["schemas"]["ActivityStatus"];
        };
        CursorPageResponseMemberMakersListResponse: {
            content?: components["schemas"]["MemberMakersListResponse"][];
            /** Format: int32 */
            size?: number;
            hasNext?: boolean;
            /** Format: int64 */
            nextCursor?: number;
            /** Format: int64 */
            totalCount?: number;
        };
        MemberMakersListResponse: {
            /** Format: int64 */
            memberActivityId?: number;
            name?: string;
            email?: string;
            phoneNumber?: string;
            jobFamily?: components["schemas"]["JobFamily"];
            makersTeam?: components["schemas"]["MakersTeam"];
            recruitTypeDetail?: components["schemas"]["RecruitTypeDetail"];
            activityStatus?: components["schemas"]["ActivityStatus"];
            memo?: string;
        };
        MemberMakersDetailResponse: {
            /** Format: int64 */
            memberActivityId?: number;
            name?: string;
            email?: string;
            phoneNumber?: string;
            jobFamily?: components["schemas"]["JobFamily"];
            careerDetails?: components["schemas"]["CareerDetails"];
            makersTeam?: components["schemas"]["MakersTeam"];
            recruitTypeDetail?: components["schemas"]["RecruitTypeDetail"];
            region?: components["schemas"]["Region"];
            interestedDomains?: string[];
            experiencePeriod?: components["schemas"]["ExperiencePeriod"];
            mentoringAvailability?: components["schemas"]["Availability"];
            projectSupplementAvailability?: components["schemas"]["Availability"];
            speakerAvailability?: components["schemas"]["Availability"];
            careerLevel?: components["schemas"]["CareerLevel"];
            activityStatus?: components["schemas"]["ActivityStatus"];
            skills?: string;
            company?: string;
            expertTopics?: string;
            activityCertNumber?: string;
            memo?: string;
        };
        MailScenarioVariableResponse: {
            /** Format: int64 */
            scenarioId?: number;
            name?: string;
            customVariables?: components["schemas"]["CustomVariableResponse"][];
            personalVariables?: string[];
        };
        /** @enum {string} */
        ApplyStatus: "JOINED" | "TEMP_SAVED" | "SUBMITTED" | "REJECTED";
        /** @enum {string} */
        RecruitType: "SEMESTER" | "MAKERS" | "SUPPORTERS" | "REGULAR" | "REGULAR_WAITLIST" | "BACKFILL" | "MANUAL";
        Pageable: {
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            sort?: string[];
        };
        AdminApplyResponse: {
            /** Format: int64 */
            applyId?: number;
            name?: string;
            phoneNumber?: string;
            email?: string;
            jobFamily?: components["schemas"]["JobFamily"];
            careerDetails?: string;
            recruitType?: string;
            note?: string;
        };
        PageAdminApplyResponse: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["AdminApplyResponse"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            /** Format: int32 */
            numberOfElements?: number;
            pageable?: components["schemas"]["PageableObject"];
            empty?: boolean;
        };
        PageableObject: {
            /** Format: int64 */
            offset?: number;
            sort?: components["schemas"]["SortObject"];
            paged?: boolean;
            /** Format: int32 */
            pageNumber?: number;
            /** Format: int32 */
            pageSize?: number;
            unpaged?: boolean;
        };
        SortObject: {
            empty?: boolean;
            sorted?: boolean;
            unsorted?: boolean;
        };
        AdminApplyDetailResponse: {
            /** Format: int64 */
            applyId?: number;
            name?: string;
            phoneNumber?: string;
            email?: string;
            jobFamily?: components["schemas"]["JobFamily"];
            careerDetails?: string;
            recruitType?: string;
            note?: string;
            region?: string;
            experiencePeriod?: string;
            interestedDomains?: string[];
        };
        /** @enum {string} */
        MemberStatus: "ACTIVE" | "LOCKED";
        AdminAccountResponse: {
            /** Format: int64 */
            id?: number;
            email?: string;
            name?: string;
            role?: components["schemas"]["Role"];
            status?: components["schemas"]["MemberStatus"];
        };
        PageAdminAccountResponse: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["AdminAccountResponse"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            /** Format: int32 */
            numberOfElements?: number;
            pageable?: components["schemas"]["PageableObject"];
            empty?: boolean;
        };
        /** @description 지원서 일괄 삭제 요청 */
        SubmittedApplyBulkDeleteRequest: {
            /**
             * @description 삭제할 지원서 ID 목록
             * @example [
             *       1,
             *       2,
             *       3
             *     ]
             */
            applyIds: number[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    updateRecruit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recruitId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecruitUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cancelRecruit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recruitId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateRecruit_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recruitId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecruitUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateScenario: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenarioId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MailScenarioRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MailScenarioResponse"];
                };
            };
        };
    };
    deleteScenario: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenarioId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    findApply: {
        parameters: {
            query?: {
                applyStatus?: components["schemas"]["ApplyStatus"];
            };
            header?: never;
            path: {
                applyId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminApplyDetailResponse"];
                };
            };
        };
    };
    editSubmittedApply: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applyId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmittedApplyEditRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteApply: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applyId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SemesterRegisterRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getEvents: {
        parameters: {
            query: {
                type: components["schemas"]["SemesterEventType"];
            };
            header?: never;
            path: {
                semesterId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SemesterEventsResponse"];
                };
            };
        };
    };
    editEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                semesterId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditSemesterEventsRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    registerRecruit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecruitRegisterRequest"][];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAdminMemberSupportersList: {
        parameters: {
            query?: {
                cursor?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CursorPageResponseMemberSupportersListResponse"];
                };
            };
        };
    };
    createAdminMemberSupporters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMemberSupportersRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    searchAdminMemberSemesterList: {
        parameters: {
            query?: {
                cursor?: number;
                size?: number;
                semesterId?: number;
                jobFamily?: components["schemas"]["JobFamily"];
                recruitTypeDetail?: components["schemas"]["RecruitTypeDetail"];
                careerDetails?: components["schemas"]["CareerDetails"];
                teamId?: number;
                status?: components["schemas"]["ActivityStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CursorPageResponseSearchMemberSemesterResponse"];
                };
            };
        };
    };
    createAdminMemberSemester: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMemberSemesterRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAdminMemberMakersList: {
        parameters: {
            query?: {
                cursor?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CursorPageResponseMemberMakersListResponse"];
                };
            };
        };
    };
    createAdminMemberMakers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMemberMakersRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getScenarios: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MailScenarioResponse"][];
                };
            };
        };
    };
    createScenario: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MailScenarioRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MailScenarioResponse"];
                };
            };
        };
    };
    sendManualTemplatedEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendManualTemplatedEmailRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    sendManualBulkTemplatedEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendManualBulkTemplatedEmailRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    passApply: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplyPassRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": number;
                };
            };
        };
    };
    findAccounts: {
        parameters: {
            query: {
                roles?: components["schemas"]["Role"][];
                statuses?: components["schemas"]["MemberStatus"][];
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageAdminAccountResponse"];
                };
            };
        };
    };
    createAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminAccountCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logoutAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    loginAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminLoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": boolean;
                };
            };
        };
    };
    updateAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memberId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminAccountUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memberId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminAccountRoleUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateActive: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memberId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminAccountActiveUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deactivateAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminAccountBulkDeactivateRequest"][];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAdminMemberSupportersDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memberActivityId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MemberSupportersDetailResponse"];
                };
            };
        };
    };
    getAdminMemberMakersDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memberActivityId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MemberMakersDetailResponse"];
                };
            };
        };
    };
    getVariablesByScenario: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenarioId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MailScenarioVariableResponse"];
                };
            };
        };
    };
    findApplies: {
        parameters: {
            query: {
                applyStatus?: components["schemas"]["ApplyStatus"];
                semesterId?: number;
                jobFamily?: components["schemas"]["JobFamily"];
                recruitType?: components["schemas"]["RecruitType"];
                recruitTypeDetail?: components["schemas"]["RecruitTypeDetail"];
                recruitId?: number;
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageAdminApplyResponse"];
                };
            };
        };
    };
    deleteSubmittedApplies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmittedApplyBulkDeleteRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": number;
                };
            };
        };
    };
}
