/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/applicants/profile/initial": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 지원자의 최초 정보 등록
         * @description 지원자(ROLE_APPLY)가 이름과 전화번호를 처음 등록할 때 사용합니다.
         */
        put: operations["registerInitialProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applicants/pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * PIN 번호 재설정
         * @description PIN 번호를 재설정합니다.
         */
        put: operations["resetPin"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/upload/portfolios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 포트폴리오 업로드
         * @description 지원자의 포트폴리오를 업로드합니다.
         */
        post: operations["uploadPortfolios"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/upload/contents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 콘텐츠 업로드
         * @description 프로젝트 썸네일, 소개서 등 콘텐츠를 업로드합니다.
         */
        post: operations["uploadContents"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/email/send/auth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 인증 번호 발송
         * @description 지정된 이메일로 인증 번호를 발송합니다.
         */
        post: operations["sendAuthEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 리프레시 토큰을 이용한 액세스 토큰 재발급
         * @description 리프레시 토큰이 유효한 경우 새로운 액세스 토큰을 발급합니다.
         */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 인증번호 검증
         * @description 인증번호 검증만 수행하고 임시 토큰을 발급합니다.
         */
        post: operations["verifyAuthCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apply/temp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 지원서 임시 저장 조회
         * @description 지원자의 특정 공고에 대한 임시 저장 지원서를 조회합니다.
         */
        get: operations["findTempApplicationForm"];
        put?: never;
        /**
         * 지원서 임시 저장
         * @description 지원자의 특정 공고에 대한 지원서를 임시 저장합니다.
         */
        post: operations["saveApplicationTemporarily"];
        /**
         * 지원서 초기화
         * @description 지원자의 특정 공고에 대한 프로필과 임시 지원서를 제거합니다.
         */
        delete: operations["deleteProfileAndTempApplicationForm"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apply/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 지원서 제출
         * @description 지원자의 특정 공고에 대해 작성이 완료된 지원서를 제출합니다.
         */
        post: operations["submitApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apply/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 프로필 작성(저장)
         * @description 지원자의 특정 공고에 대한 프로필을 작성(저장)합니다.
         */
        post: operations["saveProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applicants/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 지원자 등록
         * @description PIN 번호를 암호화하여 지원자를 생성합니다. 인증번호 검증 후 발급받은 토큰을 통해 인증된 사용자만 접근 가능합니다.
         */
        post: operations["registerTempApplicant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/access-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * access token 발급
         * @description 개발 편의를 위한 access token 발급 API
         */
        post: operations["getToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/semesters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 전체 기수 목록 조회
         * @description 모든 기수 목록을 조회합니다.
         */
        get: operations["getAllSemesters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recruits/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 활성 모집 공고 목록 조회
         * @description 현재 지원 가능한 모집 공고 목록을 조회합니다.
         */
        get: operations["findActiveRecruitments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 프로젝트 목록 조회
         * @description 카테고리 통해 프로젝트 목록을 조회합니다.
         */
        get: operations["findProjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 프로젝트 상세 조회
         * @description 전달한 ID에 해당하는 프로젝트의 상세 내용을 조회합니다.
         */
        get: operations["findProjectDetails"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 프로젝트 현황 조회
         * @description 전체 프로젝트의 요약된 현황을 조회합니다.
         */
        get: operations["findProjectSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ministudies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 미니스터디 목록 조회
         * @description 미니스터디 목록을 조회합니다.
         */
        get: operations["findMiniStudies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jectalks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 젝톡 목록 조회
         * @description 젝톡 목록을 조회합니다.
         */
        get: operations["findJectalks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login/exist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 이메일 가입 여부 확인
         * @description 입력한 이메일이 이미 가입된 사용자인지 여부를 확인합니다.
         */
        get: operations["isExistMember"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apply/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 지원 상태 확인
         * @description 지원자의 특정 공고에 대한 지원서 제출 여부를 확인합니다.
         *     - JOINED: 프로필을 저장한 경우
         *     - TEMP_SAVED: 작성 중인 지원서가 있는 경우
         *     - SUBMITTED: 이미 지원서를 제출한 경우
         */
        get: operations["checkApplyStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apply/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 지원서 문항 목록 조회
         * @description 현재 모집 중인 지원서에 한해, 전달된 모집 공고에 해당하는 문항을 모두 조회합니다.
         */
        get: operations["findQuestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applicants/profile/initial/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 프로필 정보 최초 등록 여부 확인
         * @description 지원자의 최초 프로필 정보(이름, 전화번호) 등록 여부를 확인합니다.
         */
        get: operations["isInitialApplicant"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applicants/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 현재 로그인한 지원자 프로필 조회
         * @description 현재 로그인한 지원자의 프로필를 조회합니다.
         */
        get: operations["getCurrentApplicant"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        InitialProfileRequest: {
            name: string;
            phoneNumber: string;
        };
        UpdatePinRequest: {
            pin: string;
        };
        UploadFileRequest: {
            name?: string;
            contentType?: string;
            /** Format: int64 */
            contentLength?: number;
        };
        UploadFileResponse: {
            cdnUrl?: string;
            presignedUrl?: string;
            /** Format: date-time */
            expiration?: string;
        };
        VerifyAuthCodeRequest: {
            email?: string;
            authCode?: string;
        };
        ApplyPortfolioDto: {
            fileUrl?: string;
            fileName?: string;
            fileSize?: string;
            sequence?: string;
        };
        ApplyTemporaryRequest: {
            answers?: {
                [key: string]: string;
            };
            portfolios?: components["schemas"]["ApplyPortfolioDto"][];
        };
        SubmitApplicationRequest: {
            answers?: {
                [key: string]: string;
            };
            portfolios?: components["schemas"]["ApplyPortfolioDto"][];
        };
        ApplyProfileRequest: {
            name: string;
            phoneNumber: string;
            jobFamily: components["schemas"]["JobFamily"];
            region: components["schemas"]["Region"];
            careerDetails: components["schemas"]["CareerDetails"];
            experiencePeriod: components["schemas"]["ExperiencePeriod"];
            interestedDomains: string[];
        };
        /** @enum {string} */
        CareerDetails: "STUDENT" | "EXPECTED_GRADUATE" | "JOB_SEEKER" | "BETWEEN_JOBS" | "EMPLOYEE";
        /** @enum {string} */
        ExperiencePeriod: "NONE" | "ONE_TO_TWO" | "THREE_TO_FOUR" | "FIVE_PLUS";
        /** @enum {string} */
        JobFamily: "PM" | "PD" | "FE" | "BE" | "APP" | "SUPPORTER" | "OPS" | "INFRA" | "BX" | "ER";
        /** @enum {string} */
        Region: "SEOUL" | "GYEONGGI" | "INCHEON" | "BUSAN" | "DAEGU" | "DAEJEON" | "GWANGJU" | "ULSAN" | "SEJONG" | "GANGWON" | "CHUNGBUK" | "CHUNGNAM" | "JEONBUK" | "JEONNAM" | "GYEONGBUK" | "GYEONGNAM" | "JEJU" | "OVERSEAS";
        RegisterRequest: {
            pin: string;
        };
        EmailRequest: {
            /**
             * @description 회원 이메일
             * @example admin@ject.kr
             */
            email: string;
        };
        SemesterResponse: {
            /** Format: int64 */
            id?: number;
            name?: string;
        };
        SemesterResponses: {
            semesterResponses?: components["schemas"]["SemesterResponse"][];
        };
        ActiveRecruitmentResponse: {
            /** Format: int64 */
            recruitId?: number;
            /** Format: int64 */
            semesterId?: number;
            semesterName?: string;
            recruitType?: components["schemas"]["RecruitType"];
            recruitTypeDescription?: string;
            recruitTypeDetail?: components["schemas"]["RecruitTypeDetail"];
            recruitTypeDetailDescription?: string;
            jobFamily?: components["schemas"]["JobFamily"];
            jobFamilyDescription?: string;
            /** Format: date-time */
            startDate?: string;
            /** Format: date-time */
            endDate?: string;
        };
        ActiveRecruitmentResponses: {
            recruitments?: components["schemas"]["ActiveRecruitmentResponse"][];
        };
        /** @enum {string} */
        RecruitType: "SEMESTER" | "MAKERS" | "SUPPORTERS" | "REGULAR" | "REGULAR_WAITLIST" | "BACKFILL" | "MANUAL";
        /** @enum {string} */
        RecruitTypeDetail: "REGULAR" | "NEW" | "REFILL";
        /** @enum {string} */
        Category: "SEMESTER_1" | "SEMESTER_2" | "SEMESTER_3" | "SEMESTER_4";
        Pageable: {
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            sort?: string[];
        };
        PageProjectResponse: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["ProjectResponse"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            /** Format: int32 */
            numberOfElements?: number;
            pageable?: components["schemas"]["PageableObject"];
            empty?: boolean;
        };
        PageableObject: {
            /** Format: int64 */
            offset?: number;
            sort?: components["schemas"]["SortObject"];
            paged?: boolean;
            /** Format: int32 */
            pageNumber?: number;
            /** Format: int32 */
            pageSize?: number;
            unpaged?: boolean;
        };
        ProjectResponse: {
            /** Format: int64 */
            id?: number;
            thumbnailUrl?: string;
            name?: string;
            summary?: string;
            description?: string;
            serviceType?: string;
        };
        SortObject: {
            empty?: boolean;
            sorted?: boolean;
            unsorted?: boolean;
        };
        ProjectDetailResponse: {
            name?: string;
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
            teamMemberNames?: components["schemas"]["TeamMemberNames"];
            techStack?: string[];
            badges?: string[];
            description?: string;
            serviceUrl?: string;
            githubUrl?: string;
            bannerImageUrl?: components["schemas"]["ProjectIntroResponse"];
            sampleImageUrls?: components["schemas"]["ProjectIntroResponse"][];
            descriptionImageUrls?: components["schemas"]["ProjectIntroResponse"][];
        };
        ProjectIntroResponse: {
            imageUrl?: string;
            /** Format: int32 */
            sequence?: number;
        };
        TeamMemberNames: {
            productManagers?: string[];
            productDesigners?: string[];
            frontendDevelopers?: string[];
            backendDevelopers?: string[];
        };
        CategorySummary: {
            categoryName?: string;
            /** Format: int64 */
            count?: number;
        };
        ProjectSummaryResponse: {
            categorySummaries?: components["schemas"]["CategorySummary"][];
        };
        MiniStudyResponse: {
            /** Format: int64 */
            id?: number;
            name?: string;
            linkUrl?: string;
            imageUrl?: string;
            summary?: string;
            tag?: string;
        };
        PageMiniStudyResponse: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["MiniStudyResponse"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            /** Format: int32 */
            numberOfElements?: number;
            pageable?: components["schemas"]["PageableObject"];
            empty?: boolean;
        };
        /** @enum {string} */
        ContentType: "YOUTUBE";
        JectalkResponse: {
            /** Format: int64 */
            id?: number;
            title?: string;
            description?: string;
            contentUrl?: string;
            contentType?: components["schemas"]["ContentType"];
            thumbnailUrl?: string;
            summary?: string;
        };
        PageJectalkResponse: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["JectalkResponse"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            /** Format: int32 */
            numberOfElements?: number;
            pageable?: components["schemas"]["PageableObject"];
            empty?: boolean;
        };
        TempApplicationFormResponse: {
            jobFamily?: components["schemas"]["JobFamily"];
            answers?: {
                [key: string]: string;
            };
            portfolios?: components["schemas"]["ApplyPortfolioDto"][];
        };
        /** @enum {string} */
        ApplyStatus: "JOINED" | "TEMP_SAVED" | "SUBMITTED" | "REJECTED";
        ApplyStatusResponse: {
            status?: components["schemas"]["ApplyStatus"];
        };
        /** @enum {string} */
        InputType: "SELECT" | "TEXT" | "URL" | "FILE";
        QuestionResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int32 */
            sequence?: number;
            inputType?: components["schemas"]["InputType"];
            isRequired?: boolean;
            title?: string;
            subtitle?: string;
            label?: string;
            selectOptions?: string[];
            inputHint?: string;
            /** Format: int32 */
            maxTextLength?: number;
            /** Format: int32 */
            maxFileSize?: number;
        };
        QuestionResponses: {
            questionResponses?: components["schemas"]["QuestionResponse"][];
        };
        ApplicantProfileResponse: {
            /** Format: int64 */
            id?: number;
            name?: string;
            phoneNumber?: string;
            careerDetails?: components["schemas"]["CareerDetails"];
            region?: components["schemas"]["Region"];
            experiencePeriod?: components["schemas"]["ExperiencePeriod"];
            interestedDomains?: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    registerInitialProfile: {
        parameters: {
            query: {
                applicantId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InitialProfileRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    resetPin: {
        parameters: {
            query: {
                applicantId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePinRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    uploadPortfolios: {
        parameters: {
            query: {
                memberId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadFileRequest"][];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UploadFileResponse"][];
                };
            };
        };
    };
    uploadContents: {
        parameters: {
            query: {
                memberId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadFileRequest"][];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UploadFileResponse"][];
                };
            };
        };
    };
    sendAuthEmail: {
        parameters: {
            query: {
                /** @description 이메일 템플릿 */
                sendGroupCode: "AUTH_CODE" | "PIN_RESET";
                email: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": boolean;
                };
            };
        };
    };
    verifyAuthCode: {
        parameters: {
            query: {
                /** @description 이메일 템플릿 */
                template: "AUTH_CODE" | "PIN_RESET";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyAuthCodeRequest"];
            };
        };
        responses: {
            /** @description default response */
            default: {
                headers: {
                    /** @description 검증 토큰 */
                    verificationToken?: unknown;
                    /** @description 액세스 토큰 */
                    accessToken?: unknown;
                    /** @description 프레시레시 토큰 */
                    refreshToken?: unknown;
                    [name: string]: unknown;
                };
                content: {
                    "*/*": boolean;
                };
            };
        };
    };
    findTempApplicationForm: {
        parameters: {
            query: {
                applicantId: number;
                recruitId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TempApplicationFormResponse"];
                };
            };
        };
    };
    saveApplicationTemporarily: {
        parameters: {
            query: {
                applicantId: number;
                recruitId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplyTemporaryRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteProfileAndTempApplicationForm: {
        parameters: {
            query: {
                applicantId: number;
                recruitId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    submitApplication: {
        parameters: {
            query: {
                applicantId: number;
                recruitId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitApplicationRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    saveProfile: {
        parameters: {
            query: {
                applicantId: number;
                recruitId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplyProfileRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    registerTempApplicant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": boolean;
                };
            };
        };
    };
    getToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    getAllSemesters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SemesterResponses"];
                };
            };
        };
    };
    findActiveRecruitments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ActiveRecruitmentResponses"];
                };
            };
        };
    };
    findProjects: {
        parameters: {
            query: {
                category?: components["schemas"]["Category"];
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageProjectResponse"];
                };
            };
        };
    };
    findProjectDetails: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProjectDetailResponse"];
                };
            };
        };
    };
    findProjectSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProjectSummaryResponse"];
                };
            };
        };
    };
    findMiniStudies: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageMiniStudyResponse"];
                };
            };
        };
    };
    findJectalks: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
                /**
                 * @description 기수 (SEMESTER_1, SEMESTER_2, SEMESTER_3, SEMESTER_4)
                 * @example SEMESTER_1
                 */
                category?: components["schemas"]["Category"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageJectalkResponse"];
                };
            };
        };
    };
    isExistMember: {
        parameters: {
            query: {
                email: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": boolean;
                };
            };
        };
    };
    checkApplyStatus: {
        parameters: {
            query: {
                applicantId: number;
                recruitId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApplyStatusResponse"];
                };
            };
        };
    };
    findQuestions: {
        parameters: {
            query: {
                recruitId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["QuestionResponses"];
                };
            };
        };
    };
    isInitialApplicant: {
        parameters: {
            query: {
                applicantId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": boolean;
                };
            };
        };
    };
    getCurrentApplicant: {
        parameters: {
            query: {
                applicantId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApplicantProfileResponse"];
                };
            };
        };
    };
}
