// JECT-Study/JECT-Official-WebSite-Server의 *ErrorCode.java에서 생성한다. 직접 수정하지 않는다.
// 갱신은 `pnpm gen:errors`로 한다.

export const ERROR_CODES = {
  "ADMIN-1": { name: "NOT_FOUND_ADMIN", httpStatus: 404, message: "존재하지 않는 관리자 입니다." },
  "ADMIN-5": { name: "LOCKED_ADMIN", httpStatus: 403, message: "계정이 비활성화되어 있습니다. 관리자에게 문의해주세요." },
  "ADMIN-6": { name: "INVALID_ADMIN_CREDENTIALS", httpStatus: 401, message: "이메일 또는 비밀번호가 올바르지 않습니다." },
  "ADMIN-7": { name: "LOGIN_ATTEMPT_LIMITED", httpStatus: 429, message: "로그인 시도가 제한되었습니다. 잠시 후 다시 시도해주세요." },
  "ADMIN-8": { name: "DUPLICATE_ADMIN_EMAIL", httpStatus: 409, message: "이미 사용중인 이메일 입니다." },
  "ADMIN-9": { name: "INVALID_ADMIN_ACCOUNT_ROLE", httpStatus: 400, message: "관리자 계정 유형만 선택할 수 있습니다." },
  "ADMIN-10": { name: "CANNOT_LOCK_SELF", httpStatus: 400, message: "본인 계정은 비활성화할 수 없습니다." },
  "ADMIN-11": { name: "CANNOT_CHANGE_OWN_ADMIN_ROLE", httpStatus: 400, message: "본인 계정의 관리자 권한은 변경할 수 없습니다." },
  "MAIL-1": { name: "SCENARIO_NOT_FOUND", httpStatus: 404, message: "메일 발송 시나리오를 찾을 수 없습니다." },
  "MAIL-2": { name: "INVALID_TEMPLATE_SYNTAX", httpStatus: 400, message: "템플릿 문법이 올바르지 않습니다." },
  "MAIL-3": { name: "UNSUPPORTED_TEMPLATE_VARIABLE", httpStatus: 400, message: "허용되지 않은 템플릿 변수가 포함되어 있습니다." },
  "MAIL-4": { name: "MISSING_REQUIRED_COMMON_VARIABLE", httpStatus: 400, message: "필수 공통 변수가 누락되었습니다." },
  "MAIL-5": { name: "DUPLICATE_SCENARIO_CODE", httpStatus: 409, message: "이미 사용 중인 시나리오 코드입니다." },
  "MAIL-6": { name: "INACTIVE_SCENARIO", httpStatus: 400, message: "비활성화된 시나리오입니다." },
  "MAIL-7": { name: "RECEIVER_NOT_FOUND", httpStatus: 404, message: "수신자 정보를 찾을 수 없습니다." },
  "MAIL-8": { name: "EMPTY_RECEIVERS", httpStatus: 400, message: "수신자 목록은 비어 있을 수 없습니다." },
  "MAIL-9": { name: "DISPATCH_JOB_NOT_FOUND", httpStatus: 404, message: "메일 발송 작업을 찾을 수 없습니다." },
  "MAIL-10": { name: "INVALID_DISPATCH_JOB_STATUS", httpStatus: 400, message: "현재 상태에서는 발송 실행을 수행할 수 없습니다." },
  "MAIL-11": { name: "TEST_MAIL_SEND_FAILURE", httpStatus: 503, message: "테스트 메일 발송에 실패했습니다." },
  "GLOBAL-1": { name: "UNSUPPORTED_PARAMETER_TYPE", httpStatus: 400, message: "Unsupported parameter type" },
  "GLOBAL-2": { name: "RESOURCE_NOT_FOUND", httpStatus: 404, message: "Resource not found" },
  "GLOBAL-3": { name: "TEMPLATE_NOT_FOUND", httpStatus: 404, message: "Template file not found" },
  "GLOBAL-4": { name: "JSON_MARSHALLING_FAILURE", httpStatus: 500, message: "Json marshalling failure" },
  "GLOBAL-5": { name: "EMPTY_ACCESS_TOKEN", httpStatus: 401, message: "Empty access token" },
  "GLOBAL-6": { name: "INVALID_ACCESS_TOKEN", httpStatus: 401, message: "Invalid access token" },
  "GLOBAL-7": { name: "INVALID_PERMISSION", httpStatus: 403, message: "Invalid permission" },
  "GLOBAL-8": { name: "AUTHENTICATION_REQUIRED", httpStatus: 401, message: "Authentication is required" },
  "GLOBAL-9": { name: "OVER_PERIOD", httpStatus: 409, message: "모집 기간이 아닙니다." },
  "GLOBAL-10": { name: "MISS_REQUIRED_REQUEST_PARAMETER", httpStatus: 400, message: "Missing required parameter" },
  "GLOBAL-11": { name: "MISS_REQUEST_BODY", httpStatus: 400, message: "Missing request body" },
  "GLOBAL-12": { name: "MISS_REQUIRED_JOB_FAMILY_PARAMETER", httpStatus: 400, message: "Missing required JobFamily parameter" },
  "GLOBAL-13": { name: "AUTHENTICATION_PROCESSING_ERROR", httpStatus: 500, message: "인증 처리 중 오류가 발생했습니다." },
  "GLOBAL-14": { name: "REQUEST_METHOD_NOT_ALLOWED", httpStatus: 405, message: "Method not allowed" },
  "GLOBAL-15": { name: "METHOD_VALIDATION_FAILED", httpStatus: 400, message: "Method validation failed" },
  "APPLICANT-1": { name: "NOT_FOUND_APPLICANT", httpStatus: 404, message: "지원자를 찾을 수 없습니다." },
  "APPLICANT-2": { name: "ALREADY_EXIST_APPLICANT", httpStatus: 409, message: "이미 가입되어 있는 지원자입니다." },
  "APPLICANT-3": { name: "NOT_FOUND_SEMESTER_OF_APPLICANT", httpStatus: 404, message: "지원자의 기수를 찾을 수 없습니다." },
  "APPLICANT-4": { name: "DUPLICATE_EMAIL", httpStatus: 409, message: "이미 사용 중인 이메일입니다." },
  "APPLICANT-5": { name: "EXCEEDED_INTERESTED_DOMAINS_MAX_SIZE", httpStatus: 413, message: "관심 도메인 목록의 최대 크기를 초과했습니다." },
  "APPLY-1": { name: "NOT_FOUND_APPLY", httpStatus: 404, message: "지원 정보를 찾을 수 없습니다." },
  "APPLY-2": { name: "ALREADY_SUBMITTED", httpStatus: 409, message: "이미 지원서를 제출한 상태입니다." },
  "APPLY-3": { name: "NOT_FOUND_TEMP_APPLICATION_FORM", httpStatus: 404, message: "임시 저장한 지원서가 존재하지 않습니다." },
  "APPLY-4": { name: "NOT_FOUND_SUBMITTED_APPLICATION_FORM", httpStatus: 404, message: "제출된 지원서가 존재하지 않습니다." },
  "APPLY-5": { name: "NOT_SUBMITTED", httpStatus: 409, message: "제출 완료된 지원서가 아닙니다." },
  "APPLY-6": { name: "PORTFOLIO_REQUIRED", httpStatus: 400, message: "포트폴리오를 필수로 제출해야 합니다." },
  "AUTH-1": { name: "INVALID_AUTH_CODE", httpStatus: 401, message: "인증 번호가 유효하지 않습니다." },
  "AUTH-2": { name: "NOT_FOUND_AUTH_CODE", httpStatus: 401, message: "인증 번호를 찾을 수 없습니다." },
  "AUTH-3": { name: "INVALID_REFRESH_TOKEN", httpStatus: 401, message: "유효하지 않은 리프레시 토큰입니다." },
  "AUTH-4": { name: "EXPIRED_REFRESH_TOKEN", httpStatus: 401, message: "만료된 리프레시 토큰입니다." },
  "AUTH-5": { name: "INVALID_CREDENTIALS", httpStatus: 401, message: "PIN 번호가 올바르지 않습니다." },
  "AUTH-6": { name: "EXPIRED_TOKEN", httpStatus: 401, message: "만료된 토큰입니다." },
  "AUTH-7": { name: "INVALID_TOKEN", httpStatus: 401, message: "유효하지 않은 토큰입니다." },
  "FILE-1": { name: "INVALID_EXTENSION", httpStatus: 400, message: "유효하지 않은 확장자입니다." },
  "FILE-2": { name: "EXCEEDED_PORTFOLIO_MAX_SIZE", httpStatus: 413, message: "첨부 가능한 포트폴리오 최대 용량을 초과했습니다." },
  "MEMBER-1": { name: "NOT_FOUND_MEMBER", httpStatus: 404, message: "구성원을 찾을 수 없습니다." },
  "MEMBER-2": { name: "ALREADY_EXIST_MEMBER", httpStatus: 409, message: "이미 가입되어 있는 구성원입니다." },
  "MEMBER-3": { name: "NOT_FOUND_SEMESTER_OF_MEMBER", httpStatus: 404, message: "구성원의 기수를 찾을 수 없습니다." },
  "MEMBER-4": { name: "DUPLICATE_EMAIL", httpStatus: 409, message: "이미 사용 중인 이메일입니다." },
  "MEMBER-5": { name: "EXCEEDED_INTERESTED_DOMAINS_MAX_SIZE", httpStatus: 413, message: "관심 도메인 목록의 최대 크기를 초과했습니다." },
  "MEMBER-6": { name: "ALREADY_EXIST_MEMBER_SEMESTER_ACTIVITY", httpStatus: 409, message: "해당 기수에 이미 등록된 일반 구성원 활동입니다." },
  "MEMBER-7": { name: "NOT_FOUND_TEAM_OF_SEMESTER", httpStatus: 404, message: "해당 기수의 팀을 찾을 수 없습니다." },
  "MEMBER-8": { name: "REQUIRED_SEMESTER_FOR_TEAM_FILTER", httpStatus: 400, message: "팀 필터를 사용할 때는 기수를 함께 선택해야 합니다." },
  "MEMBER-9": { name: "INVALID_ACTIVITY_STATUS", httpStatus: 400, message: "구성원 유형에 맞지 않는 활동 상태입니다." },
  "MEMBER-10": { name: "ALREADY_EXIST_ACTIVE_MEMBER_MAKERS_ACTIVITY", httpStatus: 409, message: "이미 활동 중인 메이커스팀 구성원입니다." },
  "MEMBER-11": { name: "INVALID_MEMBER_TYPE", httpStatus: 400, message: "구성원 유형이 올바르지 않습니다." },
  "MEMBER-12": { name: "INVALID_JOB_FAMILY", httpStatus: 400, message: "구성원 유형에 맞지 않는 직군입니다." },
  "MEMBER-13": { name: "ALREADY_EXIST_ACTIVE_MEMBER_SUPPORTERS_ACTIVITY", httpStatus: 409, message: "이미 활동 중인 운영 서포터즈 구성원입니다." },
  "MEMBER-14": { name: "INVALID_ACTIVITY_PERIOD", httpStatus: 400, message: "활동 기간이 올바르지 않습니다." },
  "PROJECT-1": { name: "NOT_FOUND_PROJECT", httpStatus: 404, message: "프로젝트를 찾을 수 없습니다." },
  "QUESTION-1": { name: "NOT_FOUND_QUESTION", httpStatus: 404, message: "해당 질문을 찾을 수 없습니다." },
  "RECRUIT-1": { name: "NOT_FOUND_RECRUIT", httpStatus: 404, message: "모집 공고를 찾을 수 없습니다." },
  "RECRUIT-2": { name: "DUPLICATED_JOB_FAMILY", httpStatus: 409, message: "이미 모집중인 직군입니다." },
  "RECRUIT-3": { name: "UPDATE_NOT_ALLOW_FOR_CLOSED", httpStatus: 409, message: "마감된 모집 정보는 수정할 수 없습니다." },
  "RECRUIT-4": { name: "INVALID_RECRUIT_TYPE_DETAIL", httpStatus: 400, message: "모집 유형과 모집 사유 조합이 올바르지 않습니다." },
  "SEMESTER-1": { name: "NOT_FOUND_RECRUITING_SEMESTER", httpStatus: 404, message: "현재 모집중인 기수가 존재하지 않습니다." },
  "SEMESTER-2": { name: "NOT_FOUND_SEMESTER", httpStatus: 404, message: "기수가 존재하지 않습니다." },
  "SEMESTER-3": { name: "NOT_FOUND_SEMESTER_EVENT", httpStatus: 404, message: "기수의 행사를 찾을 수 없습니다." },
  "SEMESTER-4": { name: "DUPLICATED_SEMESTER_EVENT_ID", httpStatus: 400, message: "중복된 행사 ID가 존재합니다." },
  "SEMESTER-5": { name: "EXCEEDED_SEMESTER_EVENT_LIMIT", httpStatus: 400, message: "기수별 행사 유형은 최대 10개까지 등록할 수 있습니다." },
  "INVALID_EMAIL_TEMPLATE": { name: "INVALID_EMAIL_TEMPLATE", httpStatus: 400, message: "유효하지 않은 메일 템플릿입니다." },
  "EMAIL_SEND_FAILURE": { name: "EMAIL_SEND_FAILURE", httpStatus: 503, message: "이메일 전송에 실패했습니다." },
  "TOO_MANY_EMAIL_REQUESTS": { name: "TOO_MANY_EMAIL_REQUESTS", httpStatus: 429, message: "이메일 전송 요청 횟수가 초과되었습니다. 잠시 후 다시 시도해주세요." },
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;

export function isErrorCode(value: string): value is ErrorCode {
  return value in ERROR_CODES;
}
